apiVersion: leaderworkerset.x-k8s.io/v1
kind: LeaderWorkerSet
metadata:
  name: llama-3-3-70b-instruct
  namespace: default
spec:
  replicas: 1
  leaderWorkerTemplate:
    size: 2
    restartPolicy: RecreateGroupOnPodRestart
    leaderTemplate:
      metadata:
        labels:
          role: leader
      spec:
        containers:
        - name: llama-3-3-70b-instruct-leader
          image: quay.io/surajd/lws-vllm:bcbcc5f
          command:
          - sh
          - -c
          - "/vllm-workspace/ray_init.sh leader --ray_cluster_size=$(LWS_GROUP_SIZE);
            python3 -m vllm.entrypoints.openai.api_server
            --port 8000
            --model meta-llama/Llama-3.3-70B-Instruct
            --tensor-parallel-size 2
            --pipeline-parallel-size 2"
          env:
          - name: HUGGING_FACE_HUB_TOKEN
            valueFrom:
              secretKeyRef:
                name: hf-token-secret
                key: token
          ports:
          - containerPort: 8000
          resources:
            limits:
              nvidia.com/gpu: "2"
            requests:
              nvidia.com/gpu: "2"
          volumeMounts:
          - name: shm
            mountPath: /dev/shm
        volumes:
        - name: shm
          emptyDir:
            medium: Memory

    workerTemplate:
      metadata:
        labels:
          role: worker
      spec:
        containers:
        - name: llama-3-3-70b-instruct-worker
          image: quay.io/surajd/lws-vllm:bcbcc5f
          command:
          - sh
          - -c
          - "/vllm-workspace/ray_init.sh worker --ray_address=$(LWS_LEADER_ADDRESS)"
          env:
          - name: HUGGING_FACE_HUB_TOKEN
            valueFrom:
              secretKeyRef:
                name: hf-token-secret
                key: token
          ports:
          - containerPort: 8000
          resources:
            limits:
              nvidia.com/gpu: "2"
            requests:
              nvidia.com/gpu: "2"
          volumeMounts:
          - name: shm
            mountPath: /dev/shm
        volumes:
        - name: shm
          emptyDir:
            medium: Memory
