apiVersion: v1
kind: Service
metadata:
  name: llama-3-3-70b-instruct-leader
  namespace: default
  labels:
    model: llama-3-3-70b-instruct
spec:
  ports:
    - name: http
      port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    leaderworkerset.sigs.k8s.io/name: llama-3-3-70b-instruct
    role: leader
  type: ClusterIP
