apiVersion: v1
kind: Service
metadata:
  name: locust
  namespace: locust
  labels:
    app: locust
spec:
  selector:
    app: locust
  ports:
  - protocol: TCP
    port: 8089
    targetPort: 8089
  type: ClusterIP
