single:
  enabled: false
  env:
    # NCCL_DEBUG: INFO

distributed:
  enabled: false
  env:
    NCCL_DEBUG: INFO
    NCCL_NET_GDR_LEVEL: SYS
    NCCL_IB_DISABLE: "0"
    # NCCL_IB_HCA: "^mlx5_8" # Exclude mlx5_8 (Ethernet)

images:
  vLLM: ghcr.io/surajssd/llm-k8s/vllm:0.11.0
  openwebui: ghcr.io/open-webui/open-webui:0.6.34

resources:
  nvidia.com/gpu: "1"

cli: ""

huggingFaceToken: false

storage:
  # Enable only one of the below storage options
  hostPath:
    enabled: false
    path: /mnt/model
  ephemeral:
    enabled: false
    storage: 1099511627776 # 1TB
