single:
  enabled: false
  env:
    # NCCL_DEBUG: INFO

distributed:
  enabled: false
  env:
    NCCL_DEBUG: INFO
    NCCL_NET_GDR_LEVEL: SYS
    NCCL_IB_DISABLE: "0"
    # NCCL_IB_HCA: "^mlx5_8" # Exclude mlx5_8 (Ethernet)

images:
  vLLM: ghcr.io/surajssd/llm-k8s/vllm:0.9.2
  openwebui: ghcr.io/open-webui/open-webui:0.6.15

resources:
  nvidia.com/gpu: "1"

cli: ""

huggingFaceToken: false

storage:
  enabled: false
  hostPath: /mnt/model
