single:
  enabled: false

distributed:
  enabled: false
  env:
    NCCL_DEBUG: INFO
    NCCL_NET_GDR_LEVEL: SYS
    NCCL_IB_DISABLE: "0"
    # NCCL_IB_HCA: "^mlx5_8" # Exclude mlx5_8 (Ethernet)

images:
  vLLM: ghcr.io/surajssd/llm-k8s/lws-vllm:0.8.5
  openwebui: ghcr.io/open-webui/open-webui:0.6.2

resources:
  nvidia.com/gpu: "1"

cli: ""

huggingFaceToken: false
