# Right now vllm metrics in the ray based distributed settings only show up in the leader.
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    model: llama-3-3-70b-instruct
  name: llama-3-3-70b-instruct-vllm-metrics
  namespace: default
spec:
  endpoints:
  - path: /metrics
    port: http
  selector:
    matchLabels:
      model: llama-3-3-70b-instruct
      role: leader
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    model: llama-3-3-70b-instruct
  name: llama-3-3-70b-instruct-ray-metrics
  namespace: default
spec:
  endpoints:
  - path: /
    port: ray-metrics
  selector:
    matchLabels:
      model: llama-3-3-70b-instruct
