apiVersion: v1
kind: Service
metadata:
  name: deepseek-v2-5-leader
  namespace: default
  labels:
    model: deepseek-v2-5
    role: leader
spec:
  ports:
    - name: http
      port: 8000
      protocol: TCP
      targetPort: 8000
    # This is just so that the servicemonitors can scrape the metrics
    - name: ray-metrics
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    leaderworkerset.sigs.k8s.io/name: deepseek-v2-5
    role: leader
  type: ClusterIP
---
# This is just so that the servicemonitors can scrape the metrics
apiVersion: v1
kind: Service
metadata:
  name: deepseek-v2-5-worker
  namespace: default
  labels:
    model: deepseek-v2-5
    role: worker
spec:
  ports:
  - name: ray-metrics
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    leaderworkerset.sigs.k8s.io/name: deepseek-v2-5
    role: worker
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: deepseek-v2-5-ray-dashboard
  namespace: default
  labels:
    model: ray-dashboard
spec:
  ports:
    - name: ray-dashboard
      port: 8265
      protocol: TCP
      targetPort: 8265
  selector:
    leaderworkerset.sigs.k8s.io/name: deepseek-v2-5
    role: leader
  type: ClusterIP
