{{ if .Values.single.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: default
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      volumes:
      - name: shm
        emptyDir:
          medium: Memory
      {{- if .Values.storage.hostPath.enabled }}
      - name: model
        hostPath:
          path: {{ .Values.storage.hostPath.path }}
          type: DirectoryOrCreate
      {{- end }}
      {{- if .Values.storage.ephemeral.enabled }}
      - name: model
        ephemeral:
          volumeClaimTemplate:
            metadata:
              labels:
                type: model-storage
            spec:
              accessModes: [ "ReadWriteOnce" ]
              storageClassName: cns-nvmedisk
              resources:
                requests:
                  storage: {{ .Values.storage.ephemeral.storage }}
      {{- end }}
      containers:
      - name: vllm
        image: {{ .Values.images.vLLM }}
        command:
        - /bin/bash
        - -xc
        - {{ .Values.cli | quote }}
        ports:
        - containerPort: 8000
        env:
        {{- if .Values.huggingFaceToken }}
        - name: HUGGING_FACE_HUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: hf-token-secret
              key: token
        {{- end }}
        {{- range $name, $value := .Values.single.env }}
        - name: {{ $name }}
          value: {{ $value | quote }}
        {{- end }}
        {{- if .Values.resources }}
        resources:
          limits:
            {{- toYaml .Values.resources | nindent 12 }}
          requests:
            {{- toYaml .Values.resources | nindent 12 }}
        {{- end }}
        volumeMounts:
        - name: shm
          mountPath: /dev/shm
        {{- if or .Values.storage.hostPath.enabled .Values.storage.ephemeral.enabled }}
        - name: model
          mountPath: /root/.cache/huggingface
        {{- end }}
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 600
      - name: openwebui
        image: {{ .Values.images.openwebui }}
        ports:
        - containerPort: 8080
        env:
        - name: OPENAI_API_BASE_URL
          value: "http://localhost:8000/v1"
        - name: AUDIO_STT_ENGINE
          value: "openai"
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 600
{{- end }}
