{{ if .Values.single.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: default
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
  - name: vllm
    protocol: TCP
    port: 8000
    targetPort: 8000

  - name: openwebui
    protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP
{{- end }}
