apiVersion: v1
kind: Service
metadata:
  name: phi-4-multimodal
  namespace: default
spec:
    selector:
      app: phi-4-multimodal
    ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      name: vllm
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: openwebui
    type: ClusterIP
