name: Build & Push LWS VLLM Container Image

on:
  push:
    branches:
    - main
    paths:
    - configs/vllm-image/**
    - .github/workflows/build-lws-vllm-image.yaml
  workflow_dispatch:

jobs:
  build_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Maximize build space
      uses: AdityaGarg8/remove-unwanted-software@v5
      with:
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        remove-codeql: 'true'
        remove-docker-images: 'true'
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor}}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Generate tags
      id: tag
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/surajssd/llm-k8s/vllm
        tags: |
          type=raw,value=latest
          type=raw,value=0.9.2
          type=schedule,pattern={{date 'YYYYMMDD-hhmmss' tz='America/Los_Angeles'}}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: configs/vllm-image/
        file: configs/vllm-image/Dockerfile
        push: true
        tags: ${{ steps.tag.outputs.tags }}
        labels: ${{ steps.tag.outputs.labels }}
