name: Release Charts

on:
  push:
    branches:
    - main
    paths:
    - .github/workflows/chart-releaser.yaml
    - scripts/hack/chart-releaser.sh
    - configs/chart/**

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
    - name: Setup Go
      uses: actions/setup-go@v6
    - name: Configure Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
    - name: Run Chart Releaser
      run: ./scripts/hack/chart-releaser.sh --charts-dir configs --owner surajssd --repo llm-k8s --skip-existing
      env:
        CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
